accounts/urls.py
from django.contrib.auth.views import login ,logout
from django.urls import path
from accounts.views import signup

app_name = 'accounts'

urlpatterns = [
    path("login/", login, {'template_name': 'accounts/login.html'}, name="login"),
    path("logout", logout, {'next_page': '/'}, name="logout"),
    path("signup", signup,  name="signup")
]

config/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path("", include("persons.urls", namespace="persons") ),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace="accounts"))
]

persons/urls.py
from django.urls import path
from .views import PersonListView,PersonCreateView,PersonDeleteView,PersonUpdateView
app_name = 'persons'

urlpatterns = [
    path('', PersonListView.as_view(), name='index'),
    path('create_person/', PersonCreateView.as_view(template_name='persons/create.html'), name='create_person' ),
    path('person_delete/<int:pk>/delete', PersonDeleteView.as_view(),name='delete_person'),
    path('person_delete/<int:pk>',PersonUpdateView.as_view(template_name='persons/create.html'),name='update_person'),

]

accounts/models.py
from django.db import models

# Create your models here.

persons/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone


# Create your models here.
class Person(models.Model):
    SEX = (
    ('F', 'Female'),
    ('M', 'Male'),
    )
    pub_date = models.DateField( editable=False, auto_now_add=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    comment = models.TextField()
    gender = models.CharField(max_length=1,choices=SEX)

    def __str__(self):
        return self.first_name

persons/forms.py
from django import forms
from .models import Person


class PersonForm(forms.ModelForm):

    class Meta:
        model = Person
        fields = ('first_name', 'last_name','gender','comment')

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.contrib.auth.forms import UserCreationForm

def signup(request):
    form = UserCreationForm(request.POST or None)

    if form.is_valid():
        form.save()
        password = form.cleaned_data.get('password1')
        username = form.cleaned_data.get('username')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect('persons:index')
    return render(request, "accounts/signup.html", {'form': form})

persons/views.py
from django.urls import reverse_lazy
from django.shortcuts import render, redirect
from django.views.generic import ListView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Person
from .forms import PersonForm


class PersonListView(LoginRequiredMixin,ListView):
    model = Person

    def get_context_data(self, **kwargs):
        context = super(PersonListView, self).get_context_data(**kwargs)
        context.update({
            'name': 'List Person',
            'icon':'home',
        })
        return context
    def get_queryset(self):
        results = Person.objects.filter(owner=self.request.user)
        return results

class PersonCreateView(LoginRequiredMixin, CreateView):
    form_class = PersonForm

    def form_valid(self, form):
        furmulario = form.save(commit=False)
        furmulario.owner = self.request.user
        furmulario.save()
        self.object = furmulario
        return redirect('persons:index')

    def get_context_data(self, **kwargs):
        context = super(PersonCreateView, self).get_context_data(**kwargs)
        context.update({
            'name': 'Create Person',
            'icon': 'plus-square-o'
        })
        return context



class PersonUpdateView(LoginRequiredMixin, UpdateView):
    form_class = PersonForm
    model = Person

    def form_valid(self, form):
        furmulario = form.save(commit=False)
        furmulario.owner = self.request.user
        furmulario.save()
        self.object = furmulario
        return redirect('persons:index')

    def get_context_data(self, **kwargs):
        context = super(PersonUpdateView, self).get_context_data(**kwargs)
        context.update({
            'name': 'Update Person',
            'icon':'edit',
        })
        return context


class PersonDeleteView(DeleteView):
    model = Person
    success_url = reverse_lazy('persons:index')

    def get_context_data(self, **kwargs):
        context = super(PersonDeleteView, self).get_context_data(**kwargs)
        context.update({
            'name': 'Delete Person',
            'icon': 'trash-o',
        })
        return context

templates/accounts/base_login.html
{% load static i18n %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- Main CSS-->
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %} ">
    <!-- Font-icon css-->
    <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <title>Login</title>
  </head>
  <body>
    <section class="material-half-bg">
      <div class="cover"></div>
    </section>
    <section class="login-content">
      <div class="logo">
        <h1>Pygabo</h1>
      </div>
      <div class="login-box">
        <form class="login-form" method="POST"  >
            {% csrf_token %}
            {% block content %}

            {% endblock %}
        </form>
      </div>
    </section>
    <!-- Essential javascripts for application to work-->
    <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
    <script src="{% static 'js/popper.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <!-- The javascript plugin to display page loading on top-->
    <script src="{% static 'js/plugins/pace.min.js'  %}"></script>
    <script type="text/javascript">
      // Login Page Flipbox control
      $('.login-content [data-toggle="flip"]').click(function() {
      	$('.login-box').toggleClass('flipped');
      	return false;
      });
    </script>
  </body>
</html>

templates/accounts/login.html
{% extends './base_login.html' %}
{% load crispy_forms_tags %}
{% block content %}
  {% csrf_token %}
  <h2 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>LOG IN</h2>
  {{ form|crispy }}
  <div class="form-group">
    <div class="utility">
      <div class="animated-checkbox">
      </div>
      <h5 class="semibold-text mb-2" ><a href="{% url 'accounts:signup' %}">Sign Up</a></h5>
    </div>
  </div>
  <div class="form-group btn-container">
    <button type="submit"  class="btn btn-primary btn-block"><i class="fa fa-sign-in fa-lg fa-fw"></i>LOG IN</button>
  </div>
  <script>
    document.getElementById("id_username").placeholder = "Username";
    document.getElementById("id_password").placeholder="Password";
  </script>
  <style>
    label{
        display: none;
    }
  </style>
{% endblock %}

templates/accounts/signup.html
{% extends './base_login.html' %}
{% load crispy_forms_tags %}
{% block content %}
<h3 class="login-head"><i class="fa fa-lg fa-fw fa-user"></i>SIGN IN</h3>
  {{ form|crispy }}

  <div class="form-group">
    <div class="utility">
      <div class="animated-checkbox">

      </div>
      <p class="semibold-text mb-2"><a href="{% url 'accounts:login' %}">Log in</a></p>
    </div>
  </div>
  <div class="form-group btn-container">
    <button type="submit"  class="btn btn-primary btn-block"><i class="fa fa-sign-in fa-lg fa-fw"></i>SIGN IN</button>
  </div>
<style>
  .form-text{
    display: none;
  }
</style>


<script>
    document.getElementById("id_username").placeholder = "Username";
    document.getElementById("id_password1").placeholder="Password";
    document.getElementById("id_password2").placeholder="Password confirmation";

  </script>
  <style>
    label{
      display: none;
    }
  </style>{% endblock %}

templates/base.html
{% load static i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}pygabo{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/favicon.ico' %}">

    {% block css %}

    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->

    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">


    {% endblock %}

  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-expand-md navbar-light bg-light">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="">pygabo</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="">About</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="">{% trans "My Profile" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a class="nav-link" href="">{% trans "Sign Out" %}</a>
              </li>
            {% else %}
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="sign-up-link" class="nav-link" href="">{% trans "Sign Up" %}</a>
              </li>
              <li class="nav-item">
                {# URL provided by django-allauth/account/urls.py #}
                <a id="log-in-link" class="nav-link" href="">{% trans "Sign In" %}</a>
              </li>
            {% endif %}
          </ul>
        </div>
      </nav>

    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Required by Bootstrap v4 beta -->
      <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->

      <script src="{% static 'js/project.js' %}"></script>


    {% endblock javascript %}
  </body>
</html>

templates/base_admin.html
{% load static i18n %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!-- Main CSS-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %} ">
  <!-- Font-icon css-->
  <link rel="stylesheet" type="text/css" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
  <title>{% block title %}pygabo{% endblock title %}</title>
</head>

<body class="app sidebar-mini rtl">
  {% include 'includes/header.html' %}
  <!-- Sidebar menu-->
  {% include 'includes/menu.html' %}
  <div>
    {% if messages %} {% for message in messages %}
    <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %} {% endif %}
    <main class="app-content">
      {% include 'includes/title.html' %}
      <div class="row">
        <div class="col-md-12">
          {% block content %} {% endblock content %}
        </div>
      </div>
    </main>

  </div>
  <!-- /container -->
  {% block modal %}{% endblock modal %} {% block javascript %}
  <!-- Essential javascripts for application to work-->
  <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
  <script src="{% static 'js/popper.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.min.js' %}"></script>
  <script src="{% static 'js/main.js' %}"></script>
  <!-- The javascript plugin to display page loading on top-->
  <script src="{% static 'js/plugins/pace.min.js' %}"></script>
  <!-- Page specific javascripts-->
  <!-- Google analytics script-->
  <script type="text/javascript">
    if (document.location.hostname == 'pratikborsadiya.in') {
      (function (i, s, o, g, r, a, m) {
        i['GoogleAnalyticsObject'] = r; i[r] = i[r] || function () {
          (i[r].q = i[r].q || []).push(arguments)
        }, i[r].l = 1 * new Date(); a = s.createElement(o),
          m = s.getElementsByTagName(o)[0]; a.async = 1; a.src = g; m.parentNode.insertBefore(a, m)
      })(window, document, 'script', '//www.google-analytics.com/analytics.js', 'ga');
      ga('create', 'UA-72504830-1', 'auto');
      ga('send', 'pageview');
    }
  </script> {% endblock javascript %}

</body>

</html>

templates/includes/header.html
<header class="app-header"><a class="app-header__logo" href="{% url 'persons:index' %}">Admin</a>
  <!-- Sidebar toggle button--><a class="app-sidebar__toggle" href="#" data-toggle="sidebar" aria-label="Hide Sidebar"></a>
  <!-- Navbar Right Menu-->
  <ul class="app-nav">

    <!--Notification Menu-->
    <li class="dropdown"><a class="app-nav__item" href="{% url 'persons:create_person' %}"  ><i class="fa fa-plus fa-lg"></i></a>

    </li>
    <!-- User Menu-->
    <li class="dropdown"><a class="app-nav__item" href="#" data-toggle="dropdown" aria-label="Open Profile Menu"><i class="fa fa-user fa-lg"></i></a>
      <ul class="dropdown-menu settings-menu dropdown-menu-right">
        <!-- <li><a class="dropdown-item" href="page-user.html"><i class="fa fa-cog fa-lg"></i> Settings</a></li>
        <li><a class="dropdown-item" href="page-user.html"><i class="fa fa-user fa-lg"></i> Profile</a></li> -->
        <li><a class="dropdown-item" href="{% url 'accounts:logout' %}"><i class="fa fa-sign-out fa-lg"></i> Logout</a></li>
      </ul>
    </li>
  </ul>
</header>

templates/includes/menu.html
<div class="app-sidebar__overlay" data-toggle="sidebar"></div>
<aside class="app-sidebar">
  <div class="app-sidebar__user">
    <div>
      <p class="app-sidebar__user-name">{{ user.get_username|title }}</p>
      <p class="app-sidebar__user-designation">Admin</p>
    </div>
  </div>
  <ul class="app-menu">

    <li class="treeview is-expanded">
      <a class="app-menu__item" href="#" data-toggle="treeview">
        <i class="app-menu__icon fa fa-dashboard"></i>
        <span class="app-menu__label">Dashboard</span>
        <i class="treeview-indicator fa fa-angle-right"></i>
      </a>
      <ul class="treeview-menu">
        <li>
          <a class="treeview-item" href="{% url 'persons:create_person' %}">
            <i class="icon fa fa-circle-o"></i> New </a>
        </li>
        <li>
          <a class="treeview-item" href="{% url 'persons:index' %}">
            <i class="icon fa fa-circle-o"></i> List </a>
        </li>

      </ul>
    </li>
  </ul>
</aside>

templates/includes/title.html
<div class="app-title">
  <div>
    <h1>
      <i class="fa fa-{{ icon }}"></i> {{ name }}</h1>
    <!-- <p>Start a beautiful journey here</p> -->
  </div>
  <ul class="app-breadcrumb breadcrumb">
    <li class="breadcrumb-item">
      <i class="fa fa-home fa-lg"></i>
    </li>
    <li class="breadcrumb-item">
      <a href="{% url 'persons:index' %}">List</a>
    </li>
  </ul>
</div>

templates/persons/create.html
{% extends "base_admin.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="tile">
  <form method="post" formenctype="multipart/form-data">
    {% csrf_token %} {{ form|crispy }}
    <div class="tile-footer">
      <button class="btn btn-primary" type="submit">Submit</button>
    </div>
  </form>
</div>
{% endblock %}

templates/persons/person_confirm_delete.html
{% extends "base_admin.html" %}
{% load crispy_forms_tags %}
{% block content %}
<div class="tile">
    <form method="post">{% csrf_token %}
        <h3 class="tile-title">Are you sure you want to delete "{{ object }}"?</h3>
        <input type="submit" value="Confirm"  class="btn bg-danger"/>
    </form>
</div>
{% endblock %}

templates/persons/person_list.html
{% extends "base_admin.html" %} {% block content %}
<div class="row">
	{% for object in object_list %}
	<div class="col-md-6">
		<div class="tile">
			<div class="tile-title-w-btn">
				<h3 class="title">{{ object.first_name|title }} {{ object.last_name|title  }}</h3>
				<div class="btn-group">
					<a class="btn btn-primary" href="{% url 'persons:update_person' pk=object.pk %}">
						<i class="fa fa-lg fa-edit"></i>
					</a>
					<a class="btn btn-primary" href="{% url 'persons:delete_person' pk=object.pk %}">
						<i class="fa fa-lg fa-trash"></i>
					</a>
				</div>
			</div>
			<div class="tile-body">
				<b> {{ object.get_gender_display }} </b>
				<br> {{ object.comment }}
			</div>
		</div>
	</div>
	{% empty %}
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-12">
				<div class="bs-component">
					<div class="alert alert-dismissible alert-info">
						<button class="close" type="button" data-dismiss="alert">×</button>
						<strong>Heads up!</strong>
						<a class="alert-link" href="{% url 'persons:create_person' %}">You have no created items! Create the first</a>.
					</div>
				</div>
			</div>
			<div class="col-12">
				<a class="btn btn-primary btn-lg" href="{% url 'persons:create_person' %}">New person</a>
			</div>
		</div>
	</div>
	{% endfor %}
</div>
{% endblock content %}